### ISSUE TITLE
Thank you for making Ready_RO

### ISSUE THREAD

**Issue by Ninjininja** [shioridotdev/ready_ro#1]
Hello. Thank you for making Ready_RO. I'm super new at this thing, and all the various repositories and options (some of them outdated) across the Internet were super confusing. Thanks to you I was able to get my home server (for just me and the kids) to work. After weeks of frustration, you made me see it was the files and not the SQL server. I hope others find your stuff as useful as I did. I know you don't take credit for making everything, but putting them together in a single place made this person stop pulling her hair. Thank you again! You're my online hero!

**Comment by shioridotdev** [comment]
You're welcome,
Thanks a lot for your message!
